Log:
  Level: warning 
  AccessPath: 
  ErrorPath: 
DnsConfigPath: 
RouteConfigPath: 
InboundConfigPath: 
OutboundConfigPath: 
ConnectionConfig:
  Handshake: 4 
  ConnIdle: 30 
  UplinkOnly: 2 
  DownlinkOnly: 4 
  BufferSize: 64 
Nodes:
  - PanelType: "NewV2board" 
    ApiConfig:
      ApiHost: "https://user.chonglangcloud.xyz"
      ApiKey: "adminweb3web3web3"
      NodeID: {{NODE_ID}}
      NodeType: Shadowsocks 
      Timeout: 30 
      EnableVless: false 
      VlessFlow: "xtls-rprx-vision" 
      SpeedLimit: 0 
      DeviceLimit: 0 
      RuleListPath: 
      DisableCustomConfig: false 
    ControllerConfig:
      ListenIP: 0.0.0.0 
      SendIP: 0.0.0.0 
      UpdatePeriodic: 60 
      EnableDNS: false 
      DNSType: AsIs 
      EnableProxyProtocol: false 
      AutoSpeedLimitConfig:
        Limit: 0 
        WarnTimes: 0 
        LimitSpeed: 0 
        LimitDuration: 0 
      GlobalDeviceLimitConfig:
        Enable: false 
        RedisAddr: 127.0.0.1:6379 
        RedisPassword: YOUR PASSWORD 
        RedisDB: 0 
        Timeout: 5 
        Expiry: 60 
      EnableFallback: false 
      FallBackConfigs:  
        - SNI: 
          Alpn: 
          Path: 
          Dest: 80 
          ProxyProtocolVer: 0 
      DisableLocalREALITYConfig: false 
      EnableREALITY: false 
      REALITYConfigs:
        Show: true 
        Dest: www.smzdm.com:443 
        ProxyProtocolVer: 0 
        ServerNames: 
          - www.smzdm.com
        PrivateKey: YOUR_PRIVATE_KEY 
        MinClientVer: 
        MaxClientVer: 
        MaxTimeDiff: 0 
        ShortIds: 
          - ""
          - 0123456789abcdef
      CertConfig:
        CertMode: dns 
        CertDomain: "node1.test.com"
        CertFile: /etc/XrayR/cert/node1.test.com.cert 
        KeyFile: /etc/XrayR/cert/node1.test.com.key
        Provider: alidns 
        Email: test@me.com
        DNSEnv: 
          ALICLOUD_ACCESS_KEY: aaa
          ALICLOUD_SECRET_KEY: bbb
